version: "3.5"
x-app-enviroment:
  &commonAppEnviroments
  DB_TYPE: 'postgres'
  APP_PORT: 3000
  DB_HOST: "pgsql"
  DB_PORT: "5432"
  DB_NAME: "db"
  DB_USERNAME: "user"
  DB_PASSWORD: "r00tr00t"
  JWT_SECTER: "dasdasdsafagshdgashdgashdASDASFDASFsadas1321"
services:
  nest:
    image: brkntyldrm/nest:latest
    volumes:
     - .:/usr/src/app
    depends_on:
      - pgsql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username=user --dbname=db"
        ]
    entrypoint: 
      [
        "yarn",
        "start:dev"
      ]
    environment: *commonAppEnviroments
    ports:
     - "3000:3000"
    networks:
      - database
  
  pgsql:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    ports: 
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "r00tr00t"
    networks:
      - database

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8050:80
    depends_on:
      - pgsql
    networks:
      - database
    healthcheck:
      test: [
        "CMD-SHELL",
        "nc -vz localhost 2>&1 | grep 'open' || exit 1"]
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=brkntyldrm1@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=r00tr00t
      - PGADMIN_CONFIG_SERVER_MODE=False

networks:
  database:

volumes:
  postgres:
  pgadmin:


    